version: '3'

services:
  # MySQL
  db:
    image: mysql:5.7
    container_name: auth_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE:      auth
      MYSQL_USER:          user
      MYSQL_PASSWORD:      password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    #    - ./db/data:/var/lib/mysql
    - ./db/conf.d:/etc/mysql/conf.d
    - ./db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
